"""remove imagen from compras_productos

Revision ID: 5ea38226e57b
Revises: a4d1e1d882dd
Create Date: 2025-11-21 18:00:17.131909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ea38226e57b'
down_revision: Union[str, Sequence[str], None] = 'a4d1e1d882dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('compras_productos', 'imagen')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compras_productos', sa.Column('imagen', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
