"""initial schema

Revision ID: a4d1e1d882dd
Revises: 
Create Date: 2025-11-21 17:14:27.409139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4d1e1d882dd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compras_productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('precio_compra', sa.Float(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('fecha_compra', sa.DateTime(), nullable=True),
    sa.Column('imagen', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compras_productos_id'), 'compras_productos', ['id'], unique=False)
    op.alter_column('mesas', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('mesas', 'tipo_tiempo')
    op.drop_column('mesas', 'tiempo_default_min')
    op.drop_column('mesas', 'total_calculado')
    op.alter_column('productos', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('productos', 'precio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('productos', 'stock',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('turnos', 'servicios_extras',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.drop_column('turnos', 'minutos_extra')
    op.drop_column('turnos', 'tiempo_estimado_min')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turnos', sa.Column('tiempo_estimado_min', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('turnos', sa.Column('minutos_extra', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('turnos', 'servicios_extras',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('productos', 'stock',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('productos', 'precio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('productos', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('mesas', sa.Column('total_calculado', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('mesas', sa.Column('tiempo_default_min', sa.INTEGER(), server_default=sa.text('60'), autoincrement=False, nullable=True))
    op.add_column('mesas', sa.Column('tipo_tiempo', sa.VARCHAR(length=20), server_default=sa.text("'limitado'::character varying"), autoincrement=False, nullable=True))
    op.alter_column('mesas', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_compras_productos_id'), table_name='compras_productos')
    op.drop_table('compras_productos')
    # ### end Alembic commands ###
